---
title: "Release Notes"
date: "08-12-2023"
date-modified: last-modified
engine: markdown
format: 
  html:
    toc: true
---

[pyodide]: https://pyodide.org/en/stable/
[python]: https://www.python.org/
[quarto]: https://quarto.org/


# 0.0.1.dev-2: ??? (??-??-????)

## Features

- Updated the version of Pyodide from 0.25.0 to 0.26.1  ([#20](https://github.com/coatless-quarto/pyodide/pull/20))
- New code cell option that set the interactive cell to be read-only. ([#4](https://github.com/coatless-quarto/pyodide/issues/4))

## Changes

- We now load the `micropip` and `pyodide_http` packages during document initialization.
  - `micropip` package allows for installation of pure Python or Pyodide-compiled Python packages.
     ([#3](https://github.com/coatless-quarto/pyodide/issues/3))
  - `pyodide_http` provides the necessary shims to ensure uses of `requests` and `urllib3` are 
     able to be processed instead of returning a URL error. ([#9](https://github.com/coatless-quarto/pyodide/issues/9))

# 0.0.1: What does the Python Say? (02-19-2024)

## Features

- Enable an interactive [Python][python] code cells using [Pyodide][pyodide] inside of a [Quarto][quarto] document.

````md
This is a pyodide code cell in a Quarto document. 

```{pyodide-python}
def say_hello(name):
  print(f"Hello there {name}"!)
```
````

- Execute code in the code cell using keyboard shortcuts:
   - Run selected code using: `[Cmd + Enter]` on macOS or `[Ctrl+Enter]`  on Windows 
   - Run the entire code area using: `[Shift+Enter]`

## Documentation

- Provided an extension documentation website at: <https://quarto.thecoatlessprofessor.com/pyodide>
- Included several [deployment templates](https://quarto.thecoatlessprofessor.com/pyodide/qpyodide-deployment-templates.html).

# 0.0.0-dev.0: One Python (08-12-2023)

## Features

- An initial proof of concept of the code cell.