---
title: "Python Interactive Code Cells"
subtitle: "Demos showing interactive use cases of Python in Your Quarto Documents"
author: "James Balamuta"
date: "08-08-2023"
format: 
  html:
    toc: true
---

Welcome to the world of interactive code cells, unlocked by the `quarto-pyodide` extension. 
These cells allow you to run Python code directly within your Quarto HTML documents, enabling real-time computations and more. Let's explore the impressive capabilities `pyodide` offers.
pyodide-enabled code cell are established by using `{pyodide-python}` in a Quarto HTML document.

# Creating pyodide-Enabled Code Cells

To create a pyodide-enabled code cell, simply use the `{pyodide-python}` tag in your Quarto HTML document, like this:

```{pyodide-python}
1 + 1
```

For example, the code cell above, powered by `pyodide`, was generated by entering the following into the Quarto document:

```{{pyodide-python}}
1 + 1
```

# Sample Use Cases

Now, let's delve into some practical scenarios where interactive code cells shine.

## Sample Calculations

Let's start off with a quick calculation 

```{pyodide-python}
1 + 1
```

## Strings

Viewing string data

```{pyodide-python}
greet = 'Hello'
greet
```

## Retrieving prior objects

Checking string length

```{pyodide-python}
len(greet)
```


## Line-by-line Execution

In this section, we'll explore the built-in keyboard shortcuts for executing code within the interactive code cell. You can run either the selected code or specific lines or the entire cell with the following keyboard shortcuts:

- Run selected code:
  - macOS: <kbd>⌘</kbd> + <kbd>↩/Return</kbd>
  - Windows/Linux: <kbd>Ctrl</kbd> + <kbd>↩/Enter</kbd>

- To run the entire code cell, you can simply click the "Run code" button, or use the keyboard shortcut:
  - <kbd>Shift</kbd> + <kbd>↩</kbd>

Feel free to try it out in the following code cell:

```{pyodide-python}
# Try running selected code at the start of the line
print("Hello quarto-pyodide World!")

# Try highlight only -3 or 5 and pressing the keys required
# for the "selected code" approach
-3 + 5

# Finally, try running the entire code cell by using Shift + ↩
```

By using these shortcuts, you can run code conveniently and efficiently. This practice can also help you become familiar with keyboard shortcuts when transitioning to integrated development environments (IDEs) like [RStudio](https://posit.co/products/open-source/rstudio/) or [Visual Studio Code with Python](https://code.visualstudio.com/docs/languages/python).


## Preventing Modifications to Code

Code cells can be locked to their initial state by specifying `#| read-only: true`. 

::: {.panel-tabset}
## `{quarto-pyodide}` Output

```{pyodide-python}
#| read-only: true
1 + 1
```

## Cell code

```{{pyodide-python}}
#| read-only: true
1 + 1
```
:::


## Define and Call Functions

Functions can be defined in one cell and called. 

```{pyodide-python}
def square(x):
    return x**2

square(8)
```

Similarly, they persist to other cells.

```{pyodide-python}
num_list = [1, 2, 3]
[square(num)for num in num_list]
```


## Load a package

There are two types of Python packages that will work within an interactive cell. 

- pure Python packages 
  - denoted by `*py3-none-any.whl` on PyPI
- Python packages compiled for Pyodide
  - denoted by `*-cp310-cp310-emscripten_3_1_27_wasm32.whl` that require a specific Python and Emscripten versions

The latter option makes up part of the Pyodide "core" or "base" set of Python packages. 

:::{.callout-important}
Not all functionality of a Python package may be available in the browser due to limitations or different versions being present.
:::

### Loading a Pyodide core package

For packages that are part of [Pyodide core](https://pyodide.org/en/stable/usage/packages-in-pyodide.html), we've enabled _dynamic_ package detection to handle importing packages into the environment. The _dynamic_ part comes from detecting whether a Python package is being used through an import statement and automatically taking care of the installation process behind the scenes.

:::{.callout-note}
Importing a package for the first time will require more time. Subsequent import statements will be resolve quicker.
:::

```{pyodide-python}
import pandas as pd

df = pd.DataFrame({
  'Name': ['JJB', 'H', 'Alex', 'Steve'],
  'Age': [18, 25, 33, 42]
})

df
```

```{pyodide-python}
import pandas as pd 

df.Age
```

### Loading non-core Pyodide Python Packages

In the above example, everything just worked as `pandas` in available as part of [Pyodide's built-in packages](https://pyodide.org/en/stable/usage/packages-in-pyodide.html). However, if we need a package that is not part of the built-in list, then there either needs to be a pure Python wheel (no compiled code present) or a specially compiled version of the Package for Python. 

In this case, we can install the `palmerpenguins` package from PyPI with: 

```{pyodide-python}
await micropip.install([
  "palmerpenguins",
  "setuptools" # dependency
])
```

Then, we have: 

```{pyodide-python}
# Core pyodide Python package
import pandas as pd

# External Python package
from palmerpenguins import load_penguins

# Load data in the package
penguins = load_penguins()

# Display the first 5 rows of the data using Pandas
penguins.head()
```

## Graphing

We provide support for generating graphs through the interactive HTML5 backend, e.g. [`module://matplotlib_pyodide.html5_canvas_backend`](https://github.com/pyodide/matplotlib-pyodide). At the end of each graph call, you must include a `plt.show()` call for the graph to render.

```{pyodide-python}
import matplotlib.pyplot as plt

x = [1, 5, 3, -2]
y = [-5, 8, 9, 4]

plt.plot(x, y)
plt.show()
```

## External Data

Interactive cells also allow for a limited subset of operations when working with external data. For example, we can use Pandas' `read_csv()` function to ingest data from a URL. 
```{pyodide-python}
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
df.head()
```